module

public import NearlyMinimax
public import RoughRegime
public import Solution
public import Lean.Util.CollectAxioms
import all NearlyMinimax
import all NearlyMinimax.AbsolutelyContinuousPathRisk
import all NearlyMinimax.ActualBiasAllocation
import all NearlyMinimax.ActualSeparatedPacket
import all NearlyMinimax.ActualVarianceAllocation
import all NearlyMinimax.AffineCells
import all NearlyMinimax.AffineNuisanceJoint
import all NearlyMinimax.AffineNuisanceNumerator
import all NearlyMinimax.AliasTailSummation
import all NearlyMinimax.AllocatedPilotAssumptions
import all NearlyMinimax.Allocation
import all NearlyMinimax.AllocationBounds
import all NearlyMinimax.AnchoredBasis
import all NearlyMinimax.AnchoredCard
import all NearlyMinimax.AnchoredCoefficientBounds
import all NearlyMinimax.AnchoredExpansion
import all NearlyMinimax.AnchoredFeatures
import all NearlyMinimax.AnchoredFit
import all NearlyMinimax.AnchoredFitError
import all NearlyMinimax.AnchoredGeometry
import all NearlyMinimax.AnchoredGramBounds
import all NearlyMinimax.AnchoredMoments
import all NearlyMinimax.AnchoredSpectrum
import all NearlyMinimax.AtomicRules
import all NearlyMinimax.AtomicVariation
import all NearlyMinimax.BoundedHyperplaneField
import all NearlyMinimax.BoundedPairMeanOperators
import all NearlyMinimax.CardinalBandL2
import all NearlyMinimax.CardinalBandSpatial
import all NearlyMinimax.CardinalCoefficientBounds
import all NearlyMinimax.CardinalEnergyGeometric
import all NearlyMinimax.CardinalFactorJoint
import all NearlyMinimax.CardinalFactorialEnergy
import all NearlyMinimax.CardinalGlobalBandL2
import all NearlyMinimax.CardinalGlobalDefectL2
import all NearlyMinimax.CardinalIntegratedContinuity
import all NearlyMinimax.CardinalInterpolationBias
import all NearlyMinimax.CardinalPermutation
import all NearlyMinimax.CardinalProductDesign
import all NearlyMinimax.CardinalScaleTail
import all NearlyMinimax.CardinalScaleVolume
import all NearlyMinimax.CardinalScaleWeights
import all NearlyMinimax.CardinalSeparatedBand
import all NearlyMinimax.CardinalSeparatedComposition
import all NearlyMinimax.CardinalSeparatedKernel
import all NearlyMinimax.CardinalWeightedBounds
import all NearlyMinimax.CellPolynomialProjection
import all NearlyMinimax.CellProjection
import all NearlyMinimax.CenteredActivationSup
import all NearlyMinimax.CenteredPacketAnnihilation
import all NearlyMinimax.Chebyshev
import all NearlyMinimax.Clipping
import all NearlyMinimax.CoefficientPairEstimator
import all NearlyMinimax.CommonPairRisk
import all NearlyMinimax.CompactNuisanceNorm
import all NearlyMinimax.CompleteGeometryEnergyAssembly
import all NearlyMinimax.CompleteGeometryExteriorEnergy
import all NearlyMinimax.CompleteSaddleEnergy
import all NearlyMinimax.CompleteSaddleEnergyGuards
import all NearlyMinimax.CompleteSaddleEnergyWitness
import all NearlyMinimax.CompleteSaddleGeometry
import all NearlyMinimax.CompleteSaddleNumericalReduction
import all NearlyMinimax.CompleteSaddleRiskReduction
import all NearlyMinimax.CompleteSaddleSpatialSeries
import all NearlyMinimax.CompleteSourceDensityProduct
import all NearlyMinimax.CompleteSourceInvariantMass
import all NearlyMinimax.CompleteSourceMassAnnihilation
import all NearlyMinimax.CompleteSourceRows
import all NearlyMinimax.CompleteSourceSaddleMassTail
import all NearlyMinimax.CompleteSourceSaddleParameters
import all NearlyMinimax.CompleteSourceSaddleRegime
import all NearlyMinimax.ConditionalLaw
import all NearlyMinimax.CoordinatePartialBridge
import all NearlyMinimax.CubeModelRepresentation
import all NearlyMinimax.DefectTailSummation
import all NearlyMinimax.DegreeBounds
import all NearlyMinimax.DerivativeRule
import all NearlyMinimax.DesignCounts
import all NearlyMinimax.DesignProjection
import all NearlyMinimax.DyadicApproximation
import all NearlyMinimax.DyadicBiasAllocation
import all NearlyMinimax.DyadicFit
import all NearlyMinimax.DyadicFitBounds
import all NearlyMinimax.DyadicGram
import all NearlyMinimax.DyadicIncrementBias
import all NearlyMinimax.DyadicMeasurability
import all NearlyMinimax.DyadicNesting
import all NearlyMinimax.DyadicPilotFeatures
import all NearlyMinimax.DyadicPilotFieldMeasurability
import all NearlyMinimax.DyadicPilotLift
import all NearlyMinimax.DyadicPilotMultilevel
import all NearlyMinimax.DyadicPilotPointwise
import all NearlyMinimax.DyadicPilotPopulation
import all NearlyMinimax.DyadicPilotRows
import all NearlyMinimax.DyadicPilotWeakTests
import all NearlyMinimax.DyadicPopulationBias
import all NearlyMinimax.DyadicRawCoefficients
import all NearlyMinimax.DyadicSpatialRounding
import all NearlyMinimax.DyadicTaylor
import all NearlyMinimax.ElementaryPairEstimator
import all NearlyMinimax.ElementaryUpper
import all NearlyMinimax.EvenCellPairs
import all NearlyMinimax.ExactSourceCompactEnergy
import all NearlyMinimax.ExponentialOrthantTail
import all NearlyMinimax.ExponentialSpatialKernels
import all NearlyMinimax.FactorialSeriesTail
import all NearlyMinimax.FairCellSigns
import all NearlyMinimax.FieldLiftCovariance
import all NearlyMinimax.FieldPairMoments
import all NearlyMinimax.FieldPairVariance
import all NearlyMinimax.FieldTailSummation
import all NearlyMinimax.FineFieldScaleBudget
import all NearlyMinimax.FineFieldSubsetL2
import all NearlyMinimax.FineFieldSumEnergy
import all NearlyMinimax.FineFieldTimeL2
import all NearlyMinimax.FinePairActionEnvelopes
import all NearlyMinimax.FinePairAliasSpatialEnergy
import all NearlyMinimax.FinePairAllCounts
import all NearlyMinimax.FinePairCountTwoEnergy
import all NearlyMinimax.FinePairCountTwoSpatialEnergy
import all NearlyMinimax.FinePairDensityPacket
import all NearlyMinimax.FinePairEnergyGeometric
import all NearlyMinimax.FinePairEnergyUniform
import all NearlyMinimax.FinePairFactorialEnergy
import all NearlyMinimax.FinePairHyperplanePacket
import all NearlyMinimax.FinePairMatrixCost
import all NearlyMinimax.FinePairMatrixPositivity
import all NearlyMinimax.FinePairNuisanceFactorialEnergy
import all NearlyMinimax.FinePairNuisanceNorm
import all NearlyMinimax.FinePairReference
import all NearlyMinimax.FinePairResponseBounds
import all NearlyMinimax.FinePairResponseGeometry
import all NearlyMinimax.FinePairResponsePacket
import all NearlyMinimax.FinePairRowActivity
import all NearlyMinimax.FinePairRowAnnihilation
import all NearlyMinimax.FinePairRowFacts
import all NearlyMinimax.FinePairRowMass
import all NearlyMinimax.FinePairRowNondegenerate
import all NearlyMinimax.FinePairRowSource
import all NearlyMinimax.FinePairRows
import all NearlyMinimax.FinePairSaddleFactorialEnergy
import all NearlyMinimax.FinePairScoreBounds
import all NearlyMinimax.FinePairSpatialEnergy
import all NearlyMinimax.FinePairTimeCost
import all NearlyMinimax.FinePairUnionMassAnnihilation
import all NearlyMinimax.FiniteAffineHistoryMean
import all NearlyMinimax.FiniteCountEnergyAssembly
import all NearlyMinimax.FinitePartitionMoments
import all NearlyMinimax.FiniteSigmaProbability
import all NearlyMinimax.FiniteTensorPolynomialMoments
import all NearlyMinimax.GammaTailBounds
import all NearlyMinimax.GaussianAffineRepresentation
import all NearlyMinimax.GaussianHyperplaneGeometry
import all NearlyMinimax.GaussianMonomialProducts
import all NearlyMinimax.GaussianPrimitiveSeparated
import all NearlyMinimax.GaussianProjectionMean
import all NearlyMinimax.GaussianSeparatedCharacteristic
import all NearlyMinimax.GaussianSpatialDomination
import all NearlyMinimax.GaussianSum
import all NearlyMinimax.GaussianTensorCost
import all NearlyMinimax.GenericDefectNormEnergy
import all NearlyMinimax.GenericSignedLocalOperator
import all NearlyMinimax.GridMixtureDerivative
import all NearlyMinimax.GridMixtureRisk
import all NearlyMinimax.GridProjection
import all NearlyMinimax.GridProjectionRisk
import all NearlyMinimax.GridScorePath
import all NearlyMinimax.HighActivitySummation
import all NearlyMinimax.HighAffineMixedPartials
import all NearlyMinimax.HighAppendLikelihood
import all NearlyMinimax.HighCanonicalDensityMean
import all NearlyMinimax.HighCardinalRawEnvelope
import all NearlyMinimax.HighCardinalScores
import all NearlyMinimax.HighCardinalSpatialEnergy
import all NearlyMinimax.HighCenteredMark
import all NearlyMinimax.HighCenteredRowUnion
import all NearlyMinimax.HighChartInverse
import all NearlyMinimax.HighCompleteCostFlexible
import all NearlyMinimax.HighCompleteCostRisk
import all NearlyMinimax.HighCompleteGeometry
import all NearlyMinimax.HighCompleteIntrinsicCostExact
import all NearlyMinimax.HighCompletePathRisk
import all NearlyMinimax.HighCompleteSourceFrameTail
import all NearlyMinimax.HighCompleteSourceMarkedTail
import all NearlyMinimax.HighCompleteSourceSpatialTail
import all NearlyMinimax.HighCompleteSourceTail
import all NearlyMinimax.HighConditionalScoreEnergy
import all NearlyMinimax.HighDefectNuisanceNorm
import all NearlyMinimax.HighDensityUpdates
import all NearlyMinimax.HighDesignEnergySeries
import all NearlyMinimax.HighDesignScoreTransfer
import all NearlyMinimax.HighExactNormSeries
import all NearlyMinimax.HighExactSourceEnergy
import all NearlyMinimax.HighFieldRegularity
import all NearlyMinimax.HighFieldScoreEnergy
import all NearlyMinimax.HighFrameCoefficientBridge
import all NearlyMinimax.HighFrameDesignEnergy
import all NearlyMinimax.HighFrameDesignExact
import all NearlyMinimax.HighFrameEvaluation
import all NearlyMinimax.HighFrameLegality
import all NearlyMinimax.HighFrameLocalBounds
import all NearlyMinimax.HighFrameNormProduct
import all NearlyMinimax.HighFramePolynomial
import all NearlyMinimax.HighGeometryEnvelopeMonotone
import all NearlyMinimax.HighHeatSpatialEnvelope
import all NearlyMinimax.HighHistoryDensityMean
import all NearlyMinimax.HighHistoryInvariantMass
import all NearlyMinimax.HighHistoryLikelihoodScore
import all NearlyMinimax.HighHistoryMassConcentration
import all NearlyMinimax.HighIntrinsicCoefficientLegality
import all NearlyMinimax.HighIntrinsicFieldLegality
import all NearlyMinimax.HighIntrinsicFrame
import all NearlyMinimax.HighIntrinsicLocalBounds
import all NearlyMinimax.HighIntrinsicNormalizedLegality
import all NearlyMinimax.HighIntrinsicPeriodizedBounds
import all NearlyMinimax.HighIntrinsicPeriodizedHolder
import all NearlyMinimax.HighLikelihoodDerivative
import all NearlyMinimax.HighLocalFrame
import all NearlyMinimax.HighLocalScores
import all NearlyMinimax.HighMarginalLikelihood
import all NearlyMinimax.HighMarginalScore
import all NearlyMinimax.HighMarginalScoreCenter
import all NearlyMinimax.HighMarginalScoreDerivative
import all NearlyMinimax.HighMarginalScoreEnergy
import all NearlyMinimax.HighMarkedDesignFactorial
import all NearlyMinimax.HighMarkedMeasurable
import all NearlyMinimax.HighMarkedResponseEnergy
import all NearlyMinimax.HighMarkedSelection
import all NearlyMinimax.HighMarkedSpatialDesign
import all NearlyMinimax.HighMarkedSpatialExact
import all NearlyMinimax.HighMassAnnihilation
import all NearlyMinimax.HighMassTailScale
import all NearlyMinimax.HighMassTilt
import all NearlyMinimax.HighMassTiltObservable
import all NearlyMinimax.HighNearestChart
import all NearlyMinimax.HighNormalizedCounts
import all NearlyMinimax.HighObservableProductRule
import all NearlyMinimax.HighObservableRegularity
import all NearlyMinimax.HighObservationKernel
import all NearlyMinimax.HighObservationLaw
import all NearlyMinimax.HighObservationReal
import all NearlyMinimax.HighPacketBalancing
import all NearlyMinimax.HighParameterPath
import all NearlyMinimax.HighPatchChartExact
import all NearlyMinimax.HighPatchChartMeasure
import all NearlyMinimax.HighPatchProductExact
import all NearlyMinimax.HighPatchProductMeasure
import all NearlyMinimax.HighPathBudget
import all NearlyMinimax.HighPeriodizedFrame
import all NearlyMinimax.HighPriorModel
import all NearlyMinimax.HighPriorObservableDerivative
import all NearlyMinimax.HighPriorRisk
import all NearlyMinimax.HighRawDensityLocality
import all NearlyMinimax.HighRawObservable
import all NearlyMinimax.HighRawObservableDerivative
import all NearlyMinimax.HighRawObservableRegularity
import all NearlyMinimax.HighRawScoreEnergy
import all NearlyMinimax.HighRawUpdates
import all NearlyMinimax.HighReferenceBalancing
import all NearlyMinimax.HighResponseDecoding
import all NearlyMinimax.HighResponseRemainder
import all NearlyMinimax.HighResponseTensorTail
import all NearlyMinimax.HighResponseUpdates
import all NearlyMinimax.HighRowReferenceUnion
import all NearlyMinimax.HighScoreOrthogonality
import all NearlyMinimax.HighScoreTimeKernel
import all NearlyMinimax.HighSelectedScoreEnergy
import all NearlyMinimax.HighSeparatedRows
import all NearlyMinimax.HighSeparatedScoreBounds
import all NearlyMinimax.HighSeparatedScores
import all NearlyMinimax.HighSmoothnessWindows
import all NearlyMinimax.HighSourceAffineTail
import all NearlyMinimax.HighSourceAllGeometry
import all NearlyMinimax.HighSourceCanonicalAction
import all NearlyMinimax.HighSourceCanonicalResponse
import all NearlyMinimax.HighSourceCountCancellation
import all NearlyMinimax.HighSourceFinalDecomposition
import all NearlyMinimax.HighSourceFineAliasIdentification
import all NearlyMinimax.HighSourceHigherCounts
import all NearlyMinimax.HighSourceHigherGeometry
import all NearlyMinimax.HighSourceMatchedPacket
import all NearlyMinimax.HighSourceNuisanceAction
import all NearlyMinimax.HighSourceNuisanceGeometry
import all NearlyMinimax.HighSourceNuisanceJoint
import all NearlyMinimax.HighSourceNuisanceNorm
import all NearlyMinimax.HighSourceOriginalGeometry
import all NearlyMinimax.HighSourceOriginalGuards
import all NearlyMinimax.HighSourceOriginalPair
import all NearlyMinimax.HighSourceOriginalResponse
import all NearlyMinimax.HighSourceRawDecomposition
import all NearlyMinimax.HighSourceRowTail
import all NearlyMinimax.HighSourceUnionAction
import all NearlyMinimax.HighSpatialEnvelopes
import all NearlyMinimax.HighSpatialScoreExact
import all NearlyMinimax.HighSpatialScoreTransfer
import all NearlyMinimax.HighTiltedDataMean
import all NearlyMinimax.HighTiltedObservable
import all NearlyMinimax.HighTiltedScoreDerivative
import all NearlyMinimax.HighTimeLikelihood
import all NearlyMinimax.HighTimeMarginal
import all NearlyMinimax.HighTorusScores
import all NearlyMinimax.HighUnionDensityCancellation
import all NearlyMinimax.HighUnionFieldScore
import all NearlyMinimax.HighUnionFisher
import all NearlyMinimax.HighUnionFisherExact
import all NearlyMinimax.HighUnionHistory
import all NearlyMinimax.HighUnionInvariantMass
import all NearlyMinimax.HighUnionLikelihoodScore
import all NearlyMinimax.HighUnionNuisanceJoint
import all NearlyMinimax.HighUnionNuisanceRegularity
import all NearlyMinimax.HighUnionObservationGuards
import all NearlyMinimax.HighUnionRawFisher
import all NearlyMinimax.HighUnionRawFisherExact
import all NearlyMinimax.HighUnionReset
import all NearlyMinimax.HighUnionScore
import all NearlyMinimax.HighUnionScorePrimitives
import all NearlyMinimax.HighUnionSource
import all NearlyMinimax.HighUnionSourceConcentration
import all NearlyMinimax.HighUnionSourceGeometry
import all NearlyMinimax.HighUnionSourceModel
import all NearlyMinimax.HighUnionSourceUniformModel
import all NearlyMinimax.HighUnionTiltedTail
import all NearlyMinimax.HighWindowFactorialEnergy
import all NearlyMinimax.HighWindowGeometry
import all NearlyMinimax.HighWindowLikelihoodAlgebra
import all NearlyMinimax.HigherBandActivity
import all NearlyMinimax.HigherBandActivityConversion
import all NearlyMinimax.HigherBandFamily
import all NearlyMinimax.HigherBandFamilyCollapse
import all NearlyMinimax.HigherBandOmissions
import all NearlyMinimax.HigherBandRawCollapse
import all NearlyMinimax.HigherBandRowSource
import all NearlyMinimax.HigherBandRows
import all NearlyMinimax.HigherBandTargetAction
import all NearlyMinimax.HigherFieldMomentL2
import all NearlyMinimax.HigherGeometryEnergyAssembly
import all NearlyMinimax.HistoryActivity
import all NearlyMinimax.HistoryAdjacentExchange
import all NearlyMinimax.HistoryAppend
import all NearlyMinimax.HistoryAppendMeasurable
import all NearlyMinimax.HistoryCanonicalDeletion
import all NearlyMinimax.HistoryComponents
import all NearlyMinimax.HistoryConnectedCount
import all NearlyMinimax.HistoryCoordinateTransport
import all NearlyMinimax.HistoryCoverConnectivity
import all NearlyMinimax.HistoryDensityDerivative
import all NearlyMinimax.HistoryDensityEmbedding
import all NearlyMinimax.HistoryDensityTransport
import all NearlyMinimax.HistoryExpectationDerivative
import all NearlyMinimax.HistoryExpectationRegularity
import all NearlyMinimax.HistoryGas
import all NearlyMinimax.HistoryHeapFold
import all NearlyMinimax.HistoryInvariantLaw
import all NearlyMinimax.HistoryInvariantObservable
import all NearlyMinimax.HistoryLabelDerivative
import all NearlyMinimax.HistoryMarkedAppend
import all NearlyMinimax.HistoryMarkedExchange
import all NearlyMinimax.HistoryMarkedStateAppend
import all NearlyMinimax.HistoryMassConcentration
import all NearlyMinimax.HistoryMaximalDelete
import all NearlyMinimax.HistoryOrderVolume
import all NearlyMinimax.HistoryPatchStateAppend
import all NearlyMinimax.HistoryPolynomial
import all NearlyMinimax.HistoryPositivity
import all NearlyMinimax.HistoryPrefixHeap
import all NearlyMinimax.HistoryPriorDensity
import all NearlyMinimax.HistoryPriorMeasureIdentity
import all NearlyMinimax.HistoryPriorWeakTransport
import all NearlyMinimax.HistoryProjection
import all NearlyMinimax.HistoryReferenceAppendTransport
import all NearlyMinimax.HistoryReferenceFiberIntegral
import all NearlyMinimax.HistoryReferenceMean
import all NearlyMinimax.HistoryReferenceMeasure
import all NearlyMinimax.HistoryReferenceSum
import all NearlyMinimax.HistoryShapeChangeVariables
import all NearlyMinimax.HistoryShapeCount
import all NearlyMinimax.HistoryShapeDegree
import all NearlyMinimax.HistoryShapes
import all NearlyMinimax.HistorySpanningWalk
import all NearlyMinimax.HistoryUpperSets
import all NearlyMinimax.HistoryWeakTransport
import all NearlyMinimax.HistoryWordTransport
import all NearlyMinimax.HolderNormConvention
import all NearlyMinimax.HolderTaylorBridge
import all NearlyMinimax.IncrementCoordinateBounds
import all NearlyMinimax.IncrementKernelMeasurability
import all NearlyMinimax.IncrementPilotCoordinates
import all NearlyMinimax.IncrementPilotFeatures
import all NearlyMinimax.IncrementPilotKernels
import all NearlyMinimax.IncrementPilotLocalization
import all NearlyMinimax.IntegratedCardinalCovariance
import all NearlyMinimax.IntrinsicProfileAmplitude
import all NearlyMinimax.InverseDerivativeFamily
import all NearlyMinimax.KernelEnergy
import all NearlyMinimax.KernelMomentBounds
import all NearlyMinimax.LabelBlockConcentration
import all NearlyMinimax.LabelBlockMeasure
import all NearlyMinimax.LiftL2
import all NearlyMinimax.LocalCutoffAlgebra
import all NearlyMinimax.LocalEnergySeries
import all NearlyMinimax.LocalNuisanceRanges
import all NearlyMinimax.LocalizationL2
import all NearlyMinimax.LogScaleChange
import all NearlyMinimax.LowMixtureDerivative
import all NearlyMinimax.LowMixtureLaw
import all NearlyMinimax.LowMixtureProbability
import all NearlyMinimax.LowSmoothness
import all NearlyMinimax.LowSmoothnessConstants
import all NearlyMinimax.LowSmoothnessGridChoice
import all NearlyMinimax.LowSmoothnessGridExperiment
import all NearlyMinimax.LowSmoothnessLower
import all NearlyMinimax.LowSmoothnessPrior
import all NearlyMinimax.LowSmoothnessRestriction
import all NearlyMinimax.LowSmoothnessVariance
import all NearlyMinimax.LowSmoothnessWindows
import all NearlyMinimax.LowerActivityHierarchy
import all NearlyMinimax.LowerAliasScale
import all NearlyMinimax.LowerEndpoint
import all NearlyMinimax.LowerPenaltyReduction
import all NearlyMinimax.LowerRMSAlgebra
import all NearlyMinimax.LowerRawCostReduction
import all NearlyMinimax.LowerSaddle
import all NearlyMinimax.LowerSaddleDegreeBounds
import all NearlyMinimax.MarginalLikelihood
import all NearlyMinimax.MaskedPilotKernel
import all NearlyMinimax.MassTiltTail
import all NearlyMinimax.MixtureRisk
import all NearlyMinimax.Model
import all NearlyMinimax.ModelRegularity
import all NearlyMinimax.MomentRules
import all NearlyMinimax.Moments
import all NearlyMinimax.MultiIndexCount
import all NearlyMinimax.NatRateConsequences
import all NearlyMinimax.NeighborScoreEnergy
import all NearlyMinimax.ObservationMoments
import all NearlyMinimax.OrdinaryFineAliasAggregation
import all NearlyMinimax.OrdinaryFineAliasFactorialTail
import all NearlyMinimax.OrdinaryFineAliasGeometryEnvelope
import all NearlyMinimax.OrdinaryFineAliasSaddleEnvelope
import all NearlyMinimax.OrdinaryFineAliasSpatialEnergy
import all NearlyMinimax.OriginalRawLiftField
import all NearlyMinimax.OscillationMGF
import all NearlyMinimax.OverlapVariance
import all NearlyMinimax.PacketAbsoluteMoments
import all NearlyMinimax.PairConditionalLaw
import all NearlyMinimax.PairCounting
import all NearlyMinimax.PairDesignMarginal
import all NearlyMinimax.PairDesignMeasure
import all NearlyMinimax.PairEvaluation
import all NearlyMinimax.PairEvaluationVariance
import all NearlyMinimax.PairGridChoice
import all NearlyMinimax.PairLocalization
import all NearlyMinimax.PairMass
import all NearlyMinimax.PairNoiseEvaluation
import all NearlyMinimax.PairOperatorMean
import all NearlyMinimax.PairPilotAssumptions
import all NearlyMinimax.PairPilotBudgets
import all NearlyMinimax.PairPilotFromScalars
import all NearlyMinimax.PairPilotMean
import all NearlyMinimax.PairRateAlgebra
import all NearlyMinimax.PairStatisticAlgebra
import all NearlyMinimax.PairUStatistic
import all NearlyMinimax.PairWindowGeometry
import all NearlyMinimax.PairWindowModel
import all NearlyMinimax.PairWindowMoments
import all NearlyMinimax.PaperCorollaries
import all NearlyMinimax.PaperDegreeGuards
import all NearlyMinimax.PaperElementaryUpper
import all NearlyMinimax.PaperGoals
import all NearlyMinimax.PaperIncrement
import all NearlyMinimax.PaperInverse
import all NearlyMinimax.PaperKernel
import all NearlyMinimax.PaperLowSmoothness
import all NearlyMinimax.PaperLowerRegime
import all NearlyMinimax.PaperLowerRegimeAliasEnvelope
import all NearlyMinimax.PaperLowerRegimeAliasIdentification
import all NearlyMinimax.PaperLowerRegimeAliasInfiniteTail
import all NearlyMinimax.PaperLowerRegimeAliasNorm
import all NearlyMinimax.PaperLowerRegimeAliasRaw
import all NearlyMinimax.PaperLowerRegimeAliasTail
import all NearlyMinimax.PaperLowerRegimeCenteredActivity
import all NearlyMinimax.PaperLowerRegimeEnvelopes
import all NearlyMinimax.PaperLowerRegimeFieldScale
import all NearlyMinimax.PaperLowerRegimeGeometryEnergy
import all NearlyMinimax.PaperLowerRegimeHierarchy
import all NearlyMinimax.PaperLowerRegimeInfiniteEnergy
import all NearlyMinimax.PaperLowerRegimeNormEnergy
import all NearlyMinimax.PaperLowerRegimeNumericAux
import all NearlyMinimax.PaperLowerRegimePairNorm
import all NearlyMinimax.PaperLowerRegimeRawCost
import all NearlyMinimax.PaperLowerRegimeSource
import all NearlyMinimax.PaperLowerSharp
import all NearlyMinimax.PaperMain
import all NearlyMinimax.PaperPairRisk
import all NearlyMinimax.PaperParametric
import all NearlyMinimax.PaperPlainUpper
import all NearlyMinimax.PaperPopulationFit
import all NearlyMinimax.PaperScorePath
import all NearlyMinimax.PaperScorePathOriginal
import all NearlyMinimax.PaperScoreRisk
import all NearlyMinimax.PaperScoreRiskNumerics
import all NearlyMinimax.PaperSeriesAllocation
import all NearlyMinimax.PaperSharpUpper
import all NearlyMinimax.PaperVarianceReserve
import all NearlyMinimax.ParametricConstants
import all NearlyMinimax.ParametricLower
import all NearlyMinimax.PathRisk
import all NearlyMinimax.PilotAnalyticToStatistics
import all NearlyMinimax.PilotCommonBounds
import all NearlyMinimax.PilotCoordinateExpansion
import all NearlyMinimax.PilotFeatures
import all NearlyMinimax.PilotFields
import all NearlyMinimax.PilotFluctuation
import all NearlyMinimax.PilotKernelEnergy
import all NearlyMinimax.PilotMasking
import all NearlyMinimax.PilotMean
import all NearlyMinimax.PilotMeanLaw
import all NearlyMinimax.PilotModelEnvelope
import all NearlyMinimax.PilotMultilevelCore
import all NearlyMinimax.PilotSectionMoments
import all NearlyMinimax.PilotSeriesEnvelope
import all NearlyMinimax.PilotTotalMoments
import all NearlyMinimax.PoissonCellField
import all NearlyMinimax.PoissonCellMomentBounds
import all NearlyMinimax.PoissonCellMoments
import all NearlyMinimax.PoissonCellPairEvents
import all NearlyMinimax.PoissonEnergyBounds
import all NearlyMinimax.PolynomialGaussian
import all NearlyMinimax.PolynomialGridProjection
import all NearlyMinimax.PolynomialLiftField
import all NearlyMinimax.PolynomialLiftFieldRawLocalization
import all NearlyMinimax.PolynomialProjectionRates
import all NearlyMinimax.PopulationInverseDerivatives
import all NearlyMinimax.PopulationMomentDerivatives
import all NearlyMinimax.PopulationPairBounds
import all NearlyMinimax.PopulationPilotCoefficients
import all NearlyMinimax.PopulationPilotMeans
import all NearlyMinimax.PopulationRowDerivatives
import all NearlyMinimax.PosteriorScoreEnergy
import all NearlyMinimax.PreconditionedPilot
import all NearlyMinimax.ProductBoundedDifferences
import all NearlyMinimax.Projection
import all NearlyMinimax.ProjectionGridChoice
import all NearlyMinimax.ProjectionMoments
import all NearlyMinimax.ProjectionRates
import all NearlyMinimax.ProjectionStatistical
import all NearlyMinimax.ProjectionStatisticalTransfer
import all NearlyMinimax.ProjectionUpper
import all NearlyMinimax.Rates
import all NearlyMinimax.RawCostAlgebra
import all NearlyMinimax.RawKernelFieldIntegral
import all NearlyMinimax.RawKernelFieldMeasurability
import all NearlyMinimax.RawLiftField
import all NearlyMinimax.RawLiftHilbert
import all NearlyMinimax.RawLiftPacketRealization
import all NearlyMinimax.ResponseConfigurationEnergy
import all NearlyMinimax.ResponseOperatorEnergy
import all NearlyMinimax.ResponseOperatorMean
import all NearlyMinimax.ResponseOperators
import all NearlyMinimax.Risk
import all NearlyMinimax.RiskIdentity
import all NearlyMinimax.SaddleAsymptotics
import all NearlyMinimax.SampleBlocks
import all NearlyMinimax.SampleRemainder
import all NearlyMinimax.SampleThirds
import all NearlyMinimax.ScoreCostAlgebra
import all NearlyMinimax.ScoreEnergyIntegral
import all NearlyMinimax.ScoreSupport
import all NearlyMinimax.SimilarInverseDerivatives
import all NearlyMinimax.SingletonRow
import all NearlyMinimax.SourceActivationActivity
import all NearlyMinimax.SourceActivitySummation
import all NearlyMinimax.SourceIncomingNuisance
import all NearlyMinimax.SourceIntrinsicNormalizedLegality
import all NearlyMinimax.SourceIntrinsicScoreLegality
import all NearlyMinimax.SourcePairActivityConversion
import all NearlyMinimax.SourceRowActivity
import all NearlyMinimax.SourceRows
import all NearlyMinimax.SourceSaddleActivation
import all NearlyMinimax.SourceSaddleActivity
import all NearlyMinimax.SourceSaddleHigherSelection
import all NearlyMinimax.SourceShrunkActivity
import all NearlyMinimax.SourceTotalActivity
import all NearlyMinimax.SpatialCardinalContinuity
import all NearlyMinimax.SpatialCardinalCovariance
import all NearlyMinimax.SpatialFineAliasPairL2
import all NearlyMinimax.SpatialGeometryFactorialEnergy
import all NearlyMinimax.SpatialLaplaceTail
import all NearlyMinimax.SpatialPairProductIntegration
import all NearlyMinimax.SpatialSubsetEnergy
import all NearlyMinimax.SpatialSubsetIntegral
import all NearlyMinimax.StabilizedRatioRisk
import all NearlyMinimax.TargetDefectBudget
import all NearlyMinimax.Ternary
import all NearlyMinimax.TernaryEffectiveInterval
import all NearlyMinimax.TernaryMeasure
import all NearlyMinimax.TwoScalarPilotVector
import all NearlyMinimax.TwoStagePairRisk
import all NearlyMinimax.TwoStageRisk
import all NearlyMinimax.UniformInverseDerivatives
import all NearlyMinimax.UniformPilotDerivatives
import all NearlyMinimax.UniformPilotStatistics
import all NearlyMinimax.UniformPopulationBounds
import all NearlyMinimax.UniformPopulationPairBounds
import all NearlyMinimax.UpperAllocationParameters
import all NearlyMinimax.UpperMasterRate
import all NearlyMinimax.UpperRiskAllocation
import all NearlyMinimax.UpperSpatialAllocation
import all NearlyMinimax.WeightedPair
import all NearlyMinimax.WeightedPilotEnergy
import all NearlyMinimax.WeightedScoreContraction
import all NearlyMinimax.WordHeap
import all RoughRegime
import all RoughRegime.Applications
import all RoughRegime.Cauchy
import all RoughRegime.Centering
import all RoughRegime.CombinedAnalytic
import all RoughRegime.CombinedPolynomial
import all RoughRegime.ComplexDerivativeBridge
import all RoughRegime.GeneralTesting
import all RoughRegime.HolderConstants
import all RoughRegime.HolderGeometry
import all RoughRegime.HolderModulus
import all RoughRegime.HolderTaylorApproximation
import all RoughRegime.HolderTaylorLine
import all RoughRegime.HolderTensor
import all RoughRegime.LiftTranslation
import all RoughRegime.LiftVariance
import all RoughRegime.Lower
import all RoughRegime.LowerMeasure
import all RoughRegime.MatrixDeterminant
import all RoughRegime.MatrixKernel
import all RoughRegime.MatrixUpper
import all RoughRegime.Model
import all RoughRegime.PolynomialCells
import all RoughRegime.PolynomialDerivatives
import all RoughRegime.Rates
import all RoughRegime.SeriesBounds
import all RoughRegime.TaylorPolynomial
import all RoughRegime.UniformCube
import all RoughRegime.Upper
import all RoughRegime.UpperCovariance
import all Solution


@[expose] public section

/-! Audit every theorem declared by every imported project source module,
including generated/private declarations loaded explicitly with `import all`,
selected submitted Solution proofs, and the vendored sources.
Audit definitions as well, and reject custom project axioms and all dependencies except the three
standard logical foundations. This verifies kernel trust, not paper coverage.
-/

open Lean Elab Command

run_cmd do
  let env ← getEnv
  let mut ownModules : Std.HashSet Nat := {}
  let mut vendorModules : Std.HashSet Nat := {}
  let mut ownModuleNames : Array String := #[]
  let mut vendorModuleNames : Array String := #[]
  for mod in env.header.moduleNames do
    if let some idx := env.getModuleIdx? mod then
      if mod == `NearlyMinimax || mod == `Solution || "NearlyMinimax.".isPrefixOf mod.toString then
        ownModules := ownModules.insert idx
        ownModuleNames := ownModuleNames.push mod.toString
      if mod == `RoughRegime || "RoughRegime.".isPrefixOf mod.toString then
        vendorModules := vendorModules.insert idx
        vendorModuleNames := vendorModuleNames.push mod.toString
  let isOwn := fun n ↦ match env.getModuleIdxFor? n with
    | some idx => ownModules.contains idx
    | none => false
  let isVendor := fun n ↦ match env.getModuleIdxFor? n with
    | some idx => vendorModules.contains idx
    | none => false
  let isProject := fun n ↦ isOwn n || isVendor n
  for (n, ci) in env.constants.toList do
    if isProject n then
      if let .axiomInfo _ := ci then
        throwError "Project declares a custom axiom: {n}"
  let declarations := env.constants.toList.filter fun (n, _) ↦ isProject n
  let declarations := declarations.toArray.qsort fun a b ↦ a.1.toString < b.1.toString
  let mut rows : Array Json := #[]
  let mut privateRows : Array Json := #[]
  let mut ownTheorems := 0
  let mut vendorTheorems := 0
  for (n, ci) in declarations do
    let axioms ← collectAxioms n
    for ax in axioms do
      unless #[`propext, `Classical.choice, `Quot.sound].contains ax do
        throwError "Unapproved axiom {ax} in {n}"
    if isPrivateName n then
      privateRows := privateRows.push (Json.mkObj [
        ("name", toJson n.toString),
        ("is_theorem", toJson ci.isTheorem),
        ("axioms", toJson ((axioms.map Name.toString).qsort (· < ·)))])
    if ci.isTheorem then
      if isOwn n then ownTheorems := ownTheorems + 1
      if isVendor n then vendorTheorems := vendorTheorems + 1
      rows := rows.push (Json.mkObj [
        ("theorem", toJson n.toString),
        ("origin", toJson (if isOwn n then "NearlyMinimax" else "vendored_RoughRegime")),
        ("axioms", toJson ((axioms.map Name.toString).qsort (· < ·)))])
  logInfo (Json.mkObj [
    ("schema_version", toJson (1 : Nat)),
    ("project_module_count", toJson (ownModules.size + vendorModules.size)),
    ("nearly_minimax_module_count", toJson ownModules.size),
    ("vendored_module_count", toJson vendorModules.size),
    ("declaration_count", toJson declarations.size),
    ("theorem_count", toJson rows.size),
    ("private_declaration_count", toJson privateRows.size),
    ("private_declarations", Json.arr privateRows),
    ("nearly_minimax_modules", toJson (ownModuleNames.qsort (· < ·))),
    ("vendored_modules", toJson (vendorModuleNames.qsort (· < ·))),
    ("nearly_minimax_theorem_count", toJson ownTheorems),
    ("vendored_theorem_count", toJson vendorTheorems),
    ("allowed_axioms", toJson #["propext", "Classical.choice", "Quot.sound"]),
    ("axiom_audit_passed", toJson true),
    ("theorems", Json.arr rows)]).compress
